src/aggregator/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from aggregator import views

urlpatterns = [
    path("", views.index, name="index"),
    path("q/", views.search_post, name="search_post"),
    path("myposts", views.my_posts, name="my_posts"),
    path("post/<int:post_id>", views.show_post, name="show_post"),
    path("addpost", views.add_post, name="add_post"),
    path("deletepost/<int:post_id>", views.delete_post, name="delete_post"),
    path("about", views.about, name="about"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/craigav/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("aggregator.urls")),
]

src/aggregator/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

from .categories import CATEGORIES, SUBCATEGORIES


class Category(models.Model):
    name = models.CharField(max_length=31, choices=CATEGORIES)

    class Meta:
        db_table = 'content"."category'
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Subcategory(models.Model):
    name = models.CharField(_("Name"), max_length=30, choices=SUBCATEGORIES)

    class Meta:
        db_table = 'content"."subcategory'
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Post(models.Model):
    title = models.CharField(_("Title"), max_length=50)
    description = models.CharField(_("Description"), max_length=1500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.SET_NULL, null=True)
    price = models.DecimalField(_("Price"), max_digits=12, decimal_places=2)
    city = models.CharField(_("City"), max_length=200)

    class Meta:
        db_table = 'content"."post'

    def __str__(self):
        return f"{self.title}, {self.description}, {self.price}"


class Media(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=500, null=True, blank=True)
    photo = models.ImageField(upload_to="photo/%Y/%m/%d/", null=True, blank=True)

    class Meta:
        db_table = 'content"."media'

    def __str__(self):
        return f"{self.post}, {self.name}"

src/aggregator/forms.py
from django import forms

from .categories import CATEGORIES, SUBCATEGORIES


class PostForm(forms.Form):
    title = forms.CharField(max_length=50)
    category = forms.ChoiceField(label="Category", choices=CATEGORIES)
    subcategory = forms.ChoiceField(label="SubCategory", choices=SUBCATEGORIES)
    price = forms.DecimalField(max_digits=12, decimal_places=2, min_value=0.01)
    city = forms.CharField(max_length=200)
    description = forms.CharField(widget=forms.Textarea, max_length=1500)
    photo = forms.ImageField(required=False)

    def prepopulate(post):
        initial_in_fields = {
            "title": post.title,
            "category": post.category,
            "subcategory": post.subcategory,
            "price": post.price,
            "city": post.city,
            "description": post.description,
        }
        return initial_in_fields


class EditPostForm(forms.Form):
    title = forms.CharField(max_length=50)
    category = forms.ChoiceField(label="Category", choices=CATEGORIES)
    subcategory = forms.ChoiceField(label="SubCategory", choices=SUBCATEGORIES)
    price = forms.DecimalField(max_digits=12, decimal_places=2, min_value=0.01)
    city = forms.CharField(max_length=200)
    description = forms.CharField(widget=forms.Textarea, max_length=1500)

    def prepopulate(post):
        initial_in_fields = {
            "title": post.title,
            "category": post.category,
            "subcategory": post.subcategory,
            "price": post.price,
            "city": post.city,
            "description": post.description,
        }
        return initial_in_fields

src/aggregator/views.py
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import redirect, render
from django.utils.datastructures import MultiValueDictKeyError

from . import models
from .forms import EditPostForm, PostForm


def search_post(request):
    if request.method == "GET":
        title = request.GET.get("title")
        category = request.GET.get("category")
        subcategory = request.GET.get("subcategory")
        city = request.GET.get("city")

        posts = (
            models.Post.objects.select_related("category", "subcategory", "user")
            .prefetch_related("media_set")
            .all()
        )
        if title != "":
            posts = posts.filter(Q(title__icontains=title))
        if category != "":
            posts = posts.filter(Q(category__name=category))
        if subcategory != "":
            posts = posts.filter(Q(subcategory__name=subcategory))
        if city != "":
            posts = posts.filter(Q(city__icontains=city))

        posts = posts.order_by("id")

        paginator = Paginator(posts, 3)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        context = {
            "page": page_obj,
            "title": title,
            "category": category,
            "subcategory": subcategory,
            "city": city,
        }
        return render(request, "aggregator/search_post.html", context=context)


def index(request):
    posts = models.Post.objects.prefetch_related("media_set")
    paginator = Paginator(posts, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "aggregator/index.html", {"page": page_obj})


def my_posts(request):
    if not request.user.is_authenticated:
        return redirect("/")
    posts = models.Post.objects.prefetch_related("media_set").filter(user=request.user)
    paginator = Paginator(posts, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "aggregator/my_posts.html", {"page": page_obj})


def show_post(request, post_id):
    if request.method == "POST":
        post_form = EditPostForm(request.POST, request.FILES)
        if post_form.is_valid():
            data = post_form.cleaned_data
            category = models.Category.objects.create(name=data["category"])
            subcategory = models.Subcategory.objects.create(name=data["subcategory"])
            models.Post.objects.select_related(
                "category", "subcategory", "user"
            ).prefetch_related("media_set").filter(id=post_id).update(
                title=data["title"],
                description=data["description"],
                category=category,
                subcategory=subcategory,
                price=data["price"],
                city=data["city"],
            )
            post = (
                models.Post.objects.select_related("category", "subcategory", "user")
                .prefetch_related("media_set")
                .get(id=post_id)
            )
            prepolulated_fields = EditPostForm.prepopulate(post=post)
            post_form = EditPostForm(initial=prepolulated_fields)
            return redirect("/myposts")
    else:
        post = (
            models.Post.objects.select_related("category", "subcategory", "user")
            .prefetch_related("media_set")
            .get(id=post_id)
        )
        prepolulated_fields = EditPostForm.prepopulate(post=post)
        post_form = EditPostForm(initial=prepolulated_fields)
        return render(
            request, "aggregator/post.html", {"post": post, "post_form": post_form}
        )


def add_post(request):
    if request.method == "POST":
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            data = post_form.cleaned_data
            category = models.Category.objects.create(name=data["category"])
            subcategory = models.Subcategory.objects.create(name=data["subcategory"])
            new_post = models.Post.objects.create(
                title=data["title"],
                description=data["description"],
                user=request.user,
                category=category,
                subcategory=subcategory,
                price=data["price"],
                city=data["city"],
            )
            try:
                photo = request.FILES["photo"]
                new_photo = models.Media.objects.create(
                    name=photo.name, photo=photo, post_id=new_post.id
                )
                return redirect("/")
            except MultiValueDictKeyError:
                new_photo = models.Media.objects.create(  # noqa: F841
                    name=None, photo=None, post_id=new_post.id
                )
                return redirect("/")

        else:
            return render(request, "aggregator/addpost.html", {"post_form": post_form})
    else:
        if not request.user.is_authenticated:
            return redirect("/")
        post_form = PostForm()
        return render(request, "aggregator/addpost.html", {"post_form": post_form})


def delete_post(request, post_id):
    if not request.user.is_authenticated:
        return redirect("/")
    post_to_delete = (
        models.Post.objects.select_related("category", "subcategory", "user")
        .prefetch_related("media_set")
        .get(id=post_id)
    )
    if post_to_delete.user.id != request.user.id:
        raise PermissionDenied()
    else:
        post_to_delete.delete()
        return redirect("/myposts")


def about(request):
    return render(request, "aggregator/about.html")

src/aggregator/templates/aggregator/about.html
{% extends 'aggregator/base.html' %}

{% block content %}
<div class="container about-text">
    <h2>About web-site</h2>
    <p class="lead">
        Hi and welcome to craigav!
    </p>
    <p> I made this project to demonstrate my skills in Django and Bootstrap.
        Basically this is the clone of Russian classified advertisements web-service <a href="https://avito.ru">Avito</a>
        or American <a href="http://www.craigslist.org/">Craiglist</a>. I am extremely interested in the employment abroad at the moment, so
        if you are interested in me as a potential employee please feel free to contact me via
        <a href="https://t.me/serg_serg228">telegram</a>, <a href="https://wa.me/+79205593910">whatsapp</a>,
        <a href="https://www.linkedin.com/in/sergey-koltunov-71a2971b0">linkedid</a> or my Georgian phone number: +995 551 30 62 49 (this is
        probably going to be expensive though 😅 ).
    </p>
    <p>
        My other projects can be found on <a href="https://github.com/dogbusiness">github</a>. I also recommend seeing
        my <a href="https://github.com/dogbusiness/100-days-portfolio/tree/main/day88_to_do_list">to-do list</a> project as it demonstrates skills in Flask.
        You can find my resume by clicking linkedin link. You are more than welcome to ask any questions by contacting me with the links above.
        I guess if I host some of my projects online I'll be adding links in "bio" on github profile and linkedin.
    </p>
    <p>
        Thank you for visiting web-site and I really hope you like it.
    </p>
    <p>Have a great day!</p>
</div>
{% endblock %}

src/aggregator/templates/aggregator/addpost.html
{% extends 'aggregator/base.html' %}

{% block content %}
<h2>Create New Post</h2>
    <form method="POST" class="form-group" enctype="multipart/form-data">
        {% csrf_token %}
        {{ post_form.as_p }}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
{% endblock %}

src/aggregator/templates/aggregator/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Craigav</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&amp;family=Ubuntu:wght@300&amp;display=swap" rel="stylesheet">
    <link rel="icon" href="/static/favicon.ico">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/b6b6ec4d75.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/static/css/styles.css">
</head>
{% load static %}
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand text-white" href="{% url "index" %}">
              <img class="logo" src="{% static "aggregator/logo1.png" %}">
            </a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="{% url "index" %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'about' %}">About</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item dropdown text-white">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                  {{user.username}}
                </a>
                <ul class="dropdown-menu dropdown-menu-dark bg-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'change_profile' %}">Your Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'change_password' %}">Change Password</a></li>
                  <li><a class="dropdown-item" href="{% url 'my_posts' %}">My Posts</a></li>
                  <li><hr class="dropdown-divider text-white" style="border-color:white;"></li>
                  <li><a class="dropdown-item" href="{% url 'user_logout' %}">Log Out</a></li>
                </ul>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Profile</a>
              </li>
              {% endif %}
            </ul>
            {% if user.is_authenticated %}

            <a class='btn btn-warning d-flex flex-row-reverse' href="{% url 'add_post' %}">Create a posting</a>

            {% else %}
            <a class='btn btn-warning d-flex flex-row-reverse' href="{% url 'user_register' %}">Register</a>
            <a class='login-button btn btn-warning d-flex flex-row-reverse' href="{% url 'user_login' %}">Login</a>
            {% endif %}
          </div>
        </div>
      </nav>
    {% block content %}
    {% endblock %}
    {% include "aggregator/footer.html" %}
</body>
</html>

src/aggregator/templates/aggregator/index.html
{% extends 'aggregator/base.html' %}
{% load static %}
{%block content%}

<div class="d-flex justify-content-center searchbar">
    <form method="GET" action="{% url 'search_post' %}" class="form-group row" enctype="multipart/form-data">

        <div class="col-sm-4 col-lg">
            <input class="search-element" type="text" name="title" maxlength="50" id="id_title" placeholder="Title">
        </div>

        <div class="col-sm-4 col-lg">
            <select class="search-element" name="category" id="id_category">
                <option value="">--Category--</option>

                <option value="Transport">Transport</option>

                <option value="Real Estate">Real Estate</option>

                <option value="Job">Job</option>

                <option value="Service">Service</option>

                <option value="Personal Usage">Personal Stuff</option>

                <option value="For Home">For Home</option>

                <option value="Electronics">Electronics</option>

                <option value="Hobby and Leisure">Hobby and Leisure</option>

                <option value="Pets">Pets</option>

                <option value="Business and Business Equipment">Business and Business Equipment</option>
            </select>
            </div>

        <div class="col-sm-4 col-lg">
            <select class="search-element" name="subcategory" id="id_subcategory">
                <option value="">--SubCategory--</option>

                <option value="Cars">Cars</option>

                <option value="Motorcycles">Motorcycles</option>

                <option value="Trucks">Trucks and Special Equipment</option>

                <option value="Water">Water</option>

                <option value="Parts and Accessories">Parts and Accessories</option>

                <option value="Overseas Properties">Overseas Estate</option>

                <option value="Apartments">Apartments</option>

                <option value="Rooms">Rooms</option>

                <option value="Houses">Houses</option>

                <option value="Parking">Parking</option>

                <option value="Commercial Properties">Commercial Properties</option>

                <option value="Vacancies">Vacancies</option>

                <option value="IT/Telecom">IT/Telecom</option>

                <option value="Business Services">Business Services</option>

                <option value="Tutoring">Tutoring</option>

                <option value="Building">Building</option>

                <option value="Other">Other</option>

                <option value="Clothes and Footwear">Clothes and Footwear</option>

                <option value="Clothes and Footwear for Kids">Clothes and Footwear for Kids</option>

                <option value="Baby Products and Toys">Baby Products and Toys</option>

                <option value="Accessories">Accessories</option>

                <option value="Health and Beauty">Health and Beauty</option>

                <option value="Household Equipment">Household Equipment</option>

                <option value="Furniture and Interior">Furniture and Interior</option>

                <option value="Dishes and Kitchen Equipment">Dishes and Kitchen Equipment</option>

                <option value="Groceries">Groceries</option>

                <option value="Maintenance and Building">Maintenance and Building</option>

                <option value="Plants">Plants</option>

                <option value="Audio and Video">Audio and Video</option>

                <option value="Videogaming">Videogaming</option>

                <option value="Personal Computers">Personal Computers</option>

                <option value="Laptops">Laptops</option>

                <option value="Phones">Phones</option>

                <option value="Other">Other</option>

                <option value="Tickets">Tickets</option>

                <option value="Bikes">Bikes</option>

                <option value="Books and Magazines">Books and Magazines</option>

                <option value="Collecting">Collecting</option>

                <option value="Hunting and Fishing">Hunting and Fishing</option>

                <option value="Sports and Leisure">Sports and Leisure</option>

                <option value="Dogs">Dogs</option>

                <option value="Cats">Cats</option>

                <option value="Birds">Birds</option>

                <option value="Fish">Fish</option>

                <option value="Other Pets">Other Pets</option>

                <option value="Pest Products">Pest Products</option>

                <option value="Business for Sale">Business for Sale</option>

                <option value="Business equipment">Business equipment</option>
            </select>
        </div>

        <div class="col-sm-4 col-lg">
            <input class="search-element" type="text" name="city" maxlength="200" id="id_city" placeholder="City">
        </div>

        <div class="col-sm-4 col-lg">
            <button type="submit" class="btn btn-warning search-button">
                <i class="fa-solid fa-magnifying-glass"></i>
            </button>
        </div>
    </form>
</div>
<div class="container posts">
    <div class="row">
        {% for post in page %}
            <div class="col">
                {% if post.media_set.all.0.photo %}
                <div>
                    <img src="{{post.media_set.all.0.photo.url}}" style="width:200px;height:150px;">
                </div>
                {% else %}
                <div>
                    <img src="{% static "aggregator/no-image-icon.png" %}" style="width:200px;height:150px;">
                </div>
                {% endif %}
                <div>
                    <h4><a href="{% url 'show_post' post_id=post.id %}">{{ post.title|upper }}</a></h4>
                </div>
                <div>
                    <h5>{{post.price}}$</h5>
                </div>
                <div>
                    <h6>{{post.city}}</h6>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<nav aria-label="Page navigation" class="justify-content-center">
    <ul class="pagination justify-content-center">
        {% if page.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">&lsaquo;</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a></li>
        {% endif %}
        <li class="page-item"><a class="page-link disabled">{{page.number}}</a></li>
        {% if page.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">{{ page.next_page_number }}</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">&rsaquo;</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">&raquo;</a></li>
    {% endif %}
    </ul>
  </nav>

{%endblock%}

src/aggregator/templates/aggregator/paginator_improved_not_working.html
<!-- нерабочий "улучшенный паджинатор" {#
<div class="pagination container justify-content-center" style="border: 1px; border-color: aqua; text-align: center;">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page=1">&laquo;</a>
            <a href="?page={{ page.previous_page_number }}">&lsaquo;</a>
        {% endif %}

        <span class="current">
            {{page.number}}
        </span>

        {% for pg_num in page.paginator.page_range %}
            {% if paginator.get_page(pg_num).has_next %}
                <a href="?page={{ page.paginator.get_page(pg_num).next_page_number }}">{{ page.paginator.get_page(pg_num).next_page_number }}</a>
            {% endif %}
        {% endfor %}
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">&rsaquo;</a>
            <a href="?page={{ page.paginator.num_pages }}">&raquo;</a>
        {% endif %}
    </span>
</div>
#}-->

src/aggregator/templates/aggregator/search_post.html
{% extends 'aggregator/base.html' %}
{% load static %}
{%block content%}

<div class="d-flex justify-content-center searchbar">
    <form method="GET" action="{% url 'search_post' %}" class="form-group row" enctype="multipart/form-data">

        <div class="col-sm-4 col-lg">
            <input class="search-element" type="text" name="title" maxlength="50" id="id_title" placeholder="Title">
        </div>

        <div class="col-sm-4 col-lg">
            <select class="search-element" name="category" id="id_category">
                <option value="">--Category--</option>

                <option value="Transport">Transport</option>

                <option value="Real Estate">Real Estate</option>

                <option value="Job">Job</option>

                <option value="Service">Service</option>

                <option value="Personal Usage">Personal Stuff</option>

                <option value="For Home">For Home</option>

                <option value="Electronics">Electronics</option>

                <option value="Hobby and Leisure">Hobby and Leisure</option>

                <option value="Pets">Pets</option>

                <option value="Business and Business Equipment">Business and Business Equipment</option>
            </select>
            </div>

        <div class="col-sm-4 col-lg">
            <select class="search-element" name="subcategory" id="id_subcategory">
                <option value="">--SubCategory--</option>

                <option value="Cars">Cars</option>

                <option value="Motorcycles">Motorcycles</option>

                <option value="Trucks">Trucks and Special Equipment</option>

                <option value="Water">Water</option>

                <option value="Parts and Accessories">Parts and Accessories</option>

                <option value="Overseas Properties">Overseas Estate</option>

                <option value="Apartments">Apartments</option>

                <option value="Rooms">Rooms</option>

                <option value="Houses">Houses</option>

                <option value="Parking">Parking</option>

                <option value="Commercial Properties">Commercial Properties</option>

                <option value="Vacancies">Vacancies</option>

                <option value="IT/Telecom">IT/Telecom</option>

                <option value="Business Services">Business Services</option>

                <option value="Tutoring">Tutoring</option>

                <option value="Building">Building</option>

                <option value="Other">Other</option>

                <option value="Clothes and Footwear">Clothes and Footwear</option>

                <option value="Clothes and Footwear for Kids">Clothes and Footwear for Kids</option>

                <option value="Baby Products and Toys">Baby Products and Toys</option>

                <option value="Accessories">Accessories</option>

                <option value="Health and Beauty">Health and Beauty</option>

                <option value="Household Equipment">Household Equipment</option>

                <option value="Furniture and Interior">Furniture and Interior</option>

                <option value="Dishes and Kitchen Equipment">Dishes and Kitchen Equipment</option>

                <option value="Groceries">Groceries</option>

                <option value="Maintenance and Building">Maintenance and Building</option>

                <option value="Plants">Plants</option>

                <option value="Audio and Video">Audio and Video</option>

                <option value="Videogaming">Videogaming</option>

                <option value="Personal Computers">Personal Computers</option>

                <option value="Laptops">Laptops</option>

                <option value="Phones">Phones</option>

                <option value="Other">Other</option>

                <option value="Tickets">Tickets</option>

                <option value="Bikes">Bikes</option>

                <option value="Books and Magazines">Books and Magazines</option>

                <option value="Collecting">Collecting</option>

                <option value="Hunting and Fishing">Hunting and Fishing</option>

                <option value="Sports and Leisure">Sports and Leisure</option>

                <option value="Dogs">Dogs</option>

                <option value="Cats">Cats</option>

                <option value="Birds">Birds</option>

                <option value="Fish">Fish</option>

                <option value="Other Pets">Other Pets</option>

                <option value="Pest Products">Pest Products</option>

                <option value="Business for Sale">Business for Sale</option>

                <option value="Business equipment">Business equipment</option>
            </select>
        </div>

        <div class="col-sm-4 col-lg">
            <input class="search-element" type="text" name="city" maxlength="200" id="id_city" placeholder="City">
        </div>

        <div class="col-sm-4 col-lg">
            <button type="submit" class="btn btn-warning search-button">
                <i class="fa-solid fa-magnifying-glass"></i>
            </button>
        </div>
    </form>
</div>
<div class="container posts">
    <div class="row">
        {% for post in page %}
            <div class="col">
                {% if post.media_set.all.0.photo %}
                <div>
                    <img src="{{post.media_set.all.0.photo.url}}" style="width:200px;height:150px;">
                </div>
                {% else %}
                <div>
                    <img src="{% static "aggregator/no-image-icon.png" %}" style="width:200px;height:150px;">
                </div>
                {% endif %}
                <div>
                    <h4><a href="{% url 'show_post' post_id=post.id %}">{{ post.title|upper }}</a></h4>
                </div>
                <div>
                    <h5>{{post.price}}$</h5>
                </div>
                <div>
                    <h6>{{post.city}}</h6>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<nav aria-label="Page navigation example" class="justify-content-center">
    <ul class="pagination justify-content-center">
        {% if page.has_previous %}
        <li class="page-item"><a class="page-link" href="?title={{title}}&category={{category}}&subcategory={{subcategory}}&city={{city}}&page=1">&laquo;</a></li>
        <li class="page-item"><a class="page-link" href="?title={{title}}&category={{category}}&subcategory={{subcategory}}&city={{city}}&page={{ page.previous_page_number }}">&lsaquo;</a></li>
        <li class="page-item"><a class="page-link" href="?title={{title}}&category={{category}}&subcategory={{subcategory}}&city={{city}}&page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a></li>
        {% endif %}
        <li class="page-item"><a class="page-link disabled">{{page.number}}</a></li>
        {% if page.has_next %}
        <li class="page-item"><a class="page-link" href="?title={{title}}&category={{category}}&subcategory={{subcategory}}&city={{city}}&page={{ page.next_page_number }}">{{ page.next_page_number }}</a></li>
        <li class="page-item"><a class="page-link" href="?title={{title}}&category={{category}}&subcategory={{subcategory}}&city={{city}}&page={{ page.next_page_number }}">&rsaquo;</a></li>
        <li class="page-item"><a class="page-link" href="?title={{title}}&category={{category}}&subcategory={{subcategory}}&city={{city}}&page={{ page.paginator.num_pages }}">&raquo;</a></li>
    {% endif %}
    </ul>
  </nav>
{%endblock%}